import type { Metadata } from '@/platform/types';
import { Providers } from './providers';
import { Toaster } from "@/components/Toaster"
import './globals.css';

// Self-hosted (no Google Fonts requests)
export const metadata: Metadata = {
  title: 'Cointrade',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>

        <Providers>{children}</Providers>
        <Toaster />
      </>
  );
}
